### ISSUE TITLE
cudaErrorInvalidValue(11) after execution of script

### ISSUE THREAD

**Issue by wangce94** [NVIDIA/DALI#1645]
I am trying to use DALI and TensorRT to optimize inference speed, but when I use ops.ExternalSource() to retrieve the test images, I crash at the end of my script, resulting in a core dump. Here is the error: 

> terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA runtime API error cudaErrorInvalidValue (11):
invalid argument
Aborted (core dumped)

Everything else in the script works as intended, and I can perform inference and retrieve the results. This issue does not present itself if I use FileReader() instead of ExternalSource(). However, as I am trying to include API functionalities to my script, having to save the image into a directory first can incur a lot of latency.
I ran pbd.set_trace() and managed to narrow down the exact line in which the error occurs: 

> > /usr/lib/python3.6/logging/__init__.py(1937)shutdown()->None
-> for wr in reversed(handlerList[:]):
(Pdb) n
--Call--
Exception ignored in: <async_generator object _ag at 0x7f2a193ef3f0>
Traceback (most recent call last):
  File "/usr/lib/python3.6/types.py", line 27, in _ag
  File "/usr/lib/python3.6/bdb.py", line 53, in trace_dispatch
  File "/usr/lib/python3.6/bdb.py", line 85, in dispatch_call
  File "/usr/lib/python3.6/pdb.py", line 251, in user_call
  File "/usr/lib/python3.6/pdb.py", line 351, in interaction
  File "/usr/lib/python3.6/pdb.py", line 1453, in print_stack_entry
  File "/usr/lib/python3.6/bdb.py", line 394, in format_stack_entry
TypeError: 'NoneType' object is not callable
terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA runtime API error cudaErrorInvalidValue (11):
invalid argument
Aborted (core dumped)

Here is my implementation of the ExternalSourcePipeline, and the Iterator that goes with it:

    class ExternalInputIterator(object):
        def __init__(self, batch_size):
            self.images_dir = image_dir
            self.batch_size = batch_size
            with open("testfile_list.txt", 'r') as f:
                self.files = [line.rstrip() for line in f if line is not '']
            shuffle(self.files)
            print(self.files)

        def __iter__(self):
            self.i = 0
            self.n = len(self.files)
            return self

        def __next__(self):
            batch = []
            labels = []
            for _ in range(self.batch_size):
                jpeg_filename, *label = self.files[self.i].split(' ')
                f = open(self.images_dir + jpeg_filename, 'rb')
                batch.append(np.frombuffer(f.read(), dtype = np.uint8))
                labels.append(np.array([label], dtype = np.uint8))
                self.i = (self.i + 1) % self.n
            return (batch, labels)

        next = __next__

    eii = ExternalInputIterator(batch_size)
    iterator = iter(eii)

    class ExternalSourcePipeline(Pipeline):
        def __init__(self, batch_size, num_threads, device_id):
            super(ExternalSourcePipeline, self).__init__(batch_size,
                                          num_threads,
                                          device_id,
                                          seed=12)
            self.input = ops.ExternalSource()
            self.input_label = ops.ExternalSource()
            self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
            self.res = ops.Resize(device = "gpu", resize_shorter = 256)
            self.cmnp = ops.CropMirrorNormalize(device = "gpu",
                                         output_dtype = types.FLOAT,
                                         output_layout = types.NCHW,
                                         crop = (224, 224),
                                         image_type = types.RGB,
                                         mean = [0.485 * 255,0.456 * 255,0.406 * 255],
                                         std = [0.229 * 255,0.224 * 255,0.225 * 255])

        def define_graph(self):
            self.jpegs = self.input()
            self.labels = self.input_label()
            images = self.decode(self.jpegs)
            images = self.res(images)
            output = self.cmnp(images)
            return output, self.labels

        def iter_setup(self):
            (images, labels) = iterator.next()
            self.feed_input(self.jpegs, images, layout="HWC")
            self.feed_input(self.labels, labels)

I would greatly appreciate any assistance regarding this issue. If you require any additional information, please feel free to ask and I will do my best to provide them.

**Comment by JanuszL** [comment]
Hi,
I was able to run your pipeline with images from docs/examples/images:
```
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types

batch_size = 16

class ExternalInputIterator(object):
    def __init__(self, batch_size):
        self.images_dir = "docs/examples/images/"
        self.batch_size = batch_size
        with open("docs/examples/images/file_list.txt", 'r') as f:
            self.files = [line.rstrip() for line in f if line is not '']
        shuffle(self.files)
        print(self.files)

    def __iter__(self):
        self.i = 0
        self.n = len(self.files)
        return self

    def __next__(self):
        batch = []
        labels = []
        for _ in range(self.batch_size):
            jpeg_filename, label = self.files[self.i].split(' ')
            f = open(self.images_dir + jpeg_filename, 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            labels.append(np.array([label], dtype = np.uint8))
            self.i = (self.i + 1) % self.n
        return (batch, labels)

    next = __next__

eii = ExternalInputIterator(batch_size)
iterator = iter(eii)


class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.res = ops.Resize(device = "gpu", resize_shorter = 256)
        self.cmnp = ops.CropMirrorNormalize(device = "gpu",
                                     output_dtype = types.FLOAT,
                                     output_layout = types.NCHW,
                                     crop = (224, 224),
                                     image_type = types.RGB,
                                     mean = [0.485 * 255,0.456 * 255,0.406 * 255],
                                     std = [0.229 * 255,0.224 * 255,0.225 * 255])


    def define_graph(self):
        self.jpegs = self.input()
        self.labels = self.input_label()
        images = self.decode(self.jpegs)
        images = self.res(images)
        output = self.cmnp(images)
        return output, self.labels


    def iter_setup(self):
        (images, labels) = iterator.next()
        self.feed_input(self.jpegs, images, layout="HWC")
        self.feed_input(self.labels, labels)

pipe = ExternalSourcePipeline(batch_size=batch_size, num_threads=2, device_id = 0)
pipe.build()
pipe_out = pipe.run()
```
Have you tried to just run https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html ?

**Comment by wangce94** [comment]
Hi! I have tried running it and it works fine. The issue only occurs when I try to run the ExternalInput() together with TensorRT inference. For some weird reason it works fine when I use FileReader() instead of ExternalInput()

**Comment by JanuszL** [comment]
@wangce94 - can you provide some minimal repro of that (DALI + TRT) so we can debug it on our end?

**Comment by wangce94** [comment]
Perhaps the issue has something to do with initializing the Pipeline within a class, but I wasn't able to reproduce the issue in a simplified script without all of the other things that I was doing. However, I was able to resolve the issue by manually calling del class_instance at the end of my script.

**Comment by JanuszL** [comment]
@wangce94 - it could be that pipeline has been running in the background and was trying to do something after some objects have been destructed. Without repro, it is hard to tell where exactly the problem lies.
Anyway, I'm glad you managed to figure out a workaround.

**Comment by wangce94** [comment]
Thanks for your help!
