### ISSUE TITLE
multi-machine multi-gpu training

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#2253]
![image](https://user-images.githubusercontent.com/38682321/92266750-3ec88580-ef12-11ea-96d7-b04e1a5a50c8.png)

When using multi-machine multi-gpu training, the program is stuck here. But there is no problem with single-machine multi-gpu

The code is from [here](https://github.com/NVIDIA/DALI/blob/master/docs/examples/use_cases/pytorch/resnet50/main.py)

Should it [here](https://github.com/NVIDIA/DALI/blob/aea2aa9a804e02aebd65a776f3105e27901bffff/docs/examples/use_cases/pytorch/resnet50/main.py#L147)  be changed to `shard_id=dist.get_rank()` when multi-machine multi-gpu training

**Comment by JanuszL** [comment]
Hi,
Can you add a debug message and see if your script passes through `pipe.build()`?
I can tell we run this script up to the full convergence using 8 GPU configuration for every DALI release and it works. 
And you are right, if you are training in the multi-node configuration you should use `get_rank()` instead of `local_rank()` to set `shard_id`, however the wrong value there should not cause any hang.

**Comment by pawopawo** [comment]
> Hi,
> Can you add a debug message and see if your script passes through `pipe.build()`?
> I can tell we run this script up to the full convergence using 8 GPU configuration for every DALI release and it works.
> And you are right, if you are training in the multi-node configuration you should use `get_rank()` instead of `local_rank()` to set `shard_id`, however the wrong value there should not cause any hang.

I cannot pass through `pipe.build()` when multi-node multi-gpu training

**Comment by pawopawo** [comment]
hope for help~

**Comment by JanuszL** [comment]
@pawopawo - could you try to run the training only for a single GPU but invoke it in the same way as for multi GPU one?
Honestly, I don't see any reason why it can hang on the `pipe.build()` line while ti works in `single-machine multi-gpu`. Maybe there is an issue with the mutli-gpu machine? Is it your machine or a cloud instance?

**Comment by JanuszL** [comment]
@pawopawo - if it still doesn't work please reopen.
