### ISSUE TITLE
Jetson GPU functions: CUDA runtime API error

### ISSUE THREAD

**Issue by KarelvdVrie** [NVIDIA/DALI#2926]
Hi,

I am trying to get the DALI backend for the TRITON server to work on the Jetson TX2. The problem is running any GPU functions.
I successfully cross build the python wheel for aarch64 using the steps in the documentation. Installing the wheel directly onto the Jetson or in the L4T Docker image both result in the same error.

With the following code:
```
import nvidia.dali as dali
import nvidia.dali.types as types
import numpy as np

pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=1, device_id=0, prefetch_queue_depth=1, exec_pipelined=False, exec_async=False)

with pipe:
    images = dali.fn.external_source(device="cpu", name="DALI_IMG_IN")
    images = dali.fn.decoders.image(images, device="cpu", output_type=types.RGB)
    images = dali.fn.resize(images.gpu(), device="gpu", resize_x=400.0, resize_y=320.0)
    pipe.set_outputs(images)

pipe.build()

with open("./dog.jpg", "rb") as fd:
        image_data = [np.frombuffer(fd.read(), dtype = np.uint8)]
pipe.feed_input("DALI_IMG_IN", image_data)

pipe_out = pipe.run()
```
The following image: ![dog](https://user-images.githubusercontent.com/17055112/117171339-15c30200-adcb-11eb-9959-7842763d346a.jpg)

The following error occurs:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    pipe_out = pipe.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 916, in run
    return self.outputs()
  File "/home/nvidia/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 815, in outputs
    return self._outputs()
  File "/home/nvidia/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 899, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing GPU operator Resize encountered:
CUDA runtime API error cudaErrorLaunchOutOfResources (701):
too many resources requested for launch
Current pipeline object is no longer valid.
```

If I set all the operations to CPU the pipeline runs successfully.
As far as I understood from other issues and the documentation it should be possible to use the GPU with DALI on the Jetson even thought the decoders do not support the GPU. Did I misunderstand or miss a step somewhere?

Thank you for your time.

**Comment by mzient** [comment]
We don't test with this device, so it's possible that there's an issue with block size. There's nothing that can be done at user level. However, since you're building from source, you can try and adjust the block size for this operator:
https://github.com/NVIDIA/DALI/blob/421faf043fd49a16e35308f23664835cca574fd1/dali/kernels/imgproc/resample/resampling_setup.h#L113
change 24 to 16 and see if it helps.

**Comment by KarelvdVrie** [comment]
16 did not work but 8 did the trick.
Thanks for the quick response!
