### ISSUE TITLE
Using ops.NormalDistribution

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2945]
Hi support, I want to add Gaussian noise to augment IMAGENET images.

I am using the following strategy

first I define the operation as a member in the class which inherit from DALI Pipeline 

`self.gaussian_noise = ops.NormalDistribution(device = "gpu")
`

then I define the graph using this member in the following way

`images = self.gaussian_noise(images)
`

I hope that the original images will be contaminated with Gaussian noise

It seems memory is going out of limits (RuntimeError: CUDA out of memory), maybe I will have to reduce the batch size
but I wanted to ask you 1)_ if the way I am using this ops is correct
2)_ how can I apply this noise randomly, I mean adding the noise with a x percent of chance using some kind of flipping coin?

Thanks!

Dario

**Comment by JanuszL** [comment]
Hi,
Please check [the Gaussian noise operator](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.fn.noise.gaussian) that would be available in 1.2.
In your case you need to:
```
images = self.gaussian_noise(images) + images
```
Regarding out of memory please check with smaller batch size first.
If you want to apply it conditionally you can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html).

**Comment by dariodematties** [comment]
Thank you @JanuszL ,

I am trying to use random normal bringing means and stds from outside

![image](https://user-images.githubusercontent.com/16703568/117899743-1ca3b600-b29e-11eb-9bd8-54033dfbdb61.png)

This is my pipe

![image](https://user-images.githubusercontent.com/16703568/117899813-4d83eb00-b29e-11eb-92e7-66230eb2ee58.png)
![image](https://user-images.githubusercontent.com/16703568/117899854-61c7e800-b29e-11eb-8f8e-008ef1a29d36.png)
From jupyter I try to use the pipe
![image](https://user-images.githubusercontent.com/16703568/117899947-a3f12980-b29e-11eb-906f-dc36ddebe46e.png)
But I receive the following error:
[/opt/dali/dali/pipeline/pipeline.h:176] Cannot find __ExternalSource_8 tensor, it doesn't exists or was pruned as unused one.

What I want to highlight is the fact that I am using the same strategy for bringing crop center coordinates from outside and it is working beautifully but when I want to bring means and stds for RandomNormal I do not know why thins go wrong

Any help will be highly appreciated

Thanks!

Dario

**Comment by JanuszL** [comment]
Hi @dariodematties,

The error message means that one of the outputs from an external source was not used and doesn't exist in the graph, still, you try to fill it with the data.
My quick examination of your code tells me that you are not using `guassina_std`. You should remove it.
I also recommend using [the new external source API](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) where you provide the data source directly to the operator, instead of using the `feed_data` method.

**Comment by dariodematties** [comment]
Thank you @JanuszL , yes you are right I did not use gaussian_std

Now I am using it

`images += self.gaussian_noise(images, mean=gaussian_mean, stddev=gaussian_std)
`

This is how I created the pipe

![image](https://user-images.githubusercontent.com/16703568/117965580-4fc76300-b2f9-11eb-9679-b2307ae04c77.png)

Now I am receiving the following error

```
RuntimeError: Critical error in pipeline:
Error when executing GPU operator NormalDistribution encountered:
[/opt/dali/dali/pipeline/data/views.h:53] Assert on "shape.sample_dim() == ndim" failed: Input with dimension (1) cannot be converted to dimension (0).
```
This is produced in line 504 in the pytorch wrapper

![image](https://user-images.githubusercontent.com/16703568/117966068-e136d500-b2f9-11eb-9df5-05fe77b5cbe2.png)

I don't quite understand this error...

Any suggestion?

Thanks!

Dario

**Comment by mzient** [comment]
@dariodematties It's probably about what's being fed as mean/stddev. It expects a _scalar_, not a 1-element 1D array.
You produce noise_mean as a 2D tensor `(batch, 1)` - and what DALI expect should have only `(batch)`.

**Comment by dariodematties** [comment]
Thanks so much @mzient , it is working now.

And thank you @JanuszL !!

Best!

Dario
