### ISSUE TITLE
cuStreamSynchronize failed: an illegal memory access was encountered

### ISSUE THREAD

**Issue by 980202006** [NVIDIA/DALI#4163]
```
    def exec(self):
        # context.set_shape_input(idx, tensor) 
        begin_time = time.time()
        [cuda.memcpy_htod_async(inp.device, inp.host, self.stream) for inp in self.inputs]
        self.context.execute_async(batch_size=10, bindings=self.bindings, stream_handle=self.stream.handle)
        print('execute_async Time: ', time.time() - begin_time)
        begin_time = time.time()
        for out in self.outputs:
            ww = cuda.memcpy_dtoh_async(out.host, out.device, self.stream) 
        print("memcpy_dtoh_async Time: ", time.time() - begin_time)
        begin_time = time.time()
        self.stream.synchronize()
        print('synchronize Time: ', time.time() - begin_time)
        begin_time = time.time()
        trt_output = [out.host for out in self.outputs]
        # print(trt_output[0].max(), trt_output[0].min()) 
        print('synchronize Time: ', time.time() - begin_time)
        return trt_output
    def set_input(self, dummy_input):
        ret = self.context.set_binding_shape(0, list(dummy_input[0][0].shape()))
        print(ret)
        ret = self.context.set_binding_shape(1, [dummy_input[0][0].shape()[0], 1, dummy_input[0][0].shape()[2], dummy_input[0][0].shape()[3]])
        print(ret)
        for idx, inp in enumerate(self.inputs):
        # dummy_input[idx].copy_to_external(ptr=inp.device, cuda_stream=stream)
            self.bindings[idx] = int(dummy_input[idx].data_ptr())
        self.set_input_flag = True
    def __call__(self):
        with self.context:
            out = self.exec()
        return out
```
I use dali to read the video file and then use tensorrt for inference, but maybe the assignment input is causing the illegal memory access problem.I first call self.set_input(input1, input2) to set the input, then call __call__ to execute the model, but I get an error at self.stream.synchronize().
```
Traceback (most recent call last):
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xingyum/anaconda3/envs/vis/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xingyum/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/xingyum/models/videos/ky_watermark_removal/serve/ocr_inf.py", line 110, in <module>
    model.inference('/home/xingyum/models/content_detection/525.mp4',
  File "/home/xingyum/models/videos/ky_watermark_removal/serve/ocr_inf.py", line 57, in inference
    comp_frames = self.removal_model()
  File "/home/xingyum/models/videos/ky_watermark_removal/serve/engine.py", line 90, in __call__
    out = self.exec()
  File "/home/xingyum/models/videos/ky_watermark_removal/serve/engine.py", line 78, in exec
    self.stream.synchronize()
pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered
```
If I comment self.bindings[idx] = int(dummy_input[idx].data_ptr()), this error will not be reported.

**Comment by szalpal** [comment]
Hi @980202006 ,

would you mind providing us with a repro of the error? Without it it is hard to know, what's causing the illegal memory access. Are you sure, that the `dummy_input` actually contains a valid data for the range of the indices it is called with?

**Comment by 980202006** [comment]
I found the reason, because the model needs float type, my dali data output is int.
Thanks.

**Comment by Abiganesh** [comment]
Below is my code for Tensorrt Inference.
```
import numpy as np
import os
import pycuda.driver as cuda
import pycuda.autoinit
import tensorrt as trt

import matplotlib.pyplot as plt
from PIL import Image

TRT_LOGGER = trt.Logger()

# Filenames of TensorRT plan file and input/output images.
engine_file = "efficient64.engine"
# For torchvision models, input images are loaded in to a range of [0, 1] and
# normalized using mean = [0.485, 0.456, 0.406] and stddev = [0.229, 0.224, 0.225].
def preprocess(image):
    # Mean normalization
    mean = np.array([0.485, 0.456, 0.406]).astype('float32')
    stddev = np.array([0.229, 0.224, 0.225]).astype('float32')
    data = (np.asarray(image).astype('float32') / float(255.0) - mean) / stddev
    # Switch from HWC to to CHW order
    return np.moveaxis(data, 2, 0)

def postprocess(data):
    num_classes = 2
    # create a color palette, selecting a color for each class
    palette = np.array([2 ** 25 - 1, 2 ** 15 - 1, 2 ** 21 - 1])
    colors = np.array([palette*i%255 for i in range(num_classes)]).astype("uint8")
    # plot the segmentation predictions for 21 classes in different colors
    img = Image.fromarray(data.astype('uint8'), mode='P')
    img.putpalette(colors)
    return img
def load_engine(engine_file_path):
    assert os.path.exists(engine_file_path)
    print("Reading engine from file {}".format(engine_file_path))
    with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
        return runtime.deserialize_cuda_engine(f.read())
def infer(engine, input_file, output_file):
    print("Reading input image from file {}".format(input_file))
    with Image.open(input_file) as img:
        input_image = preprocess(img)
        image_width = img.width
        image_height = img.height

    with engine.create_execution_context() as context:
        # Set input shape based on image dimensions for inference
        print(engine.get_binding_index("input"))
        context.set_binding_shape(engine.get_binding_index("input"), (1, 3, image_height, image_width))
        # Allocate host and device buffers
        bindings = []
        for binding in engine:
            
            binding_idx = engine.get_binding_index(binding)
            print("binding size",context.get_binding_shape(binding_idx))
            size = trt.volume(context.get_binding_shape(binding_idx))
            dtype = trt.nptype(engine.get_binding_dtype(binding))

            if engine.binding_is_input(binding):
                input_buffer = np.ascontiguousarray(input_image)
                input_memory = cuda.mem_alloc(input_image.nbytes)
                print("inpt byte",input_image.nbytes)
                bindings.append(int(input_memory))
            else:
                print("size",size,"dype",dtype)
                output_buffer = cuda.pagelocked_empty(size, dtype)
                print(output_buffer)
                output_memory = cuda.mem_alloc(output_buffer.nbytes)
                print("memory out",output_memory)
                bindings.append(int(output_memory))
        stream = cuda.Stream()
        #host_input = np.array(preprocess_image("2.ppm").numpy(), dtype=np.float32, order='C')
        # Transfer input data to the GPU.
        cuda.memcpy_htod_async(input_memory, input_buffer, stream)
        print("mem ",input_memory,"buff ",input_buffer)
        # Run inference
        a=context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)
        print(a)
        # Transfer prediction output from the GPU.
        cuda.memcpy_dtoh_async(output_buffer, output_memory, stream)
        print(output_buffer)
        print(output_memory)
        # Synchronize the stream
        stream.synchronize()
    

    img =postprocess(np.reshape(output_buffer, (image_height, image_width)))
    
    print("Writing output image to file {}".format(output_file))
    img.convert('RGB').save(output_file, "PPM")
input_file  = "2.ppm"
output_file = "output.ppm"
#plt.imshow(Image.open(input_file))
print("Running TensorRT inference for FCN-ResNet101")
with load_engine(engine_file) as engine:
    infer(engine, input_file, output_file)
```
I have got below memory error , how to solve that
Running TensorRT inference for FCN-ResNet101
Reading engine from file efficient64.engine
Reading input image from file 2.ppm
-1
binding size (1, 3, 1920, 1080)
inpt byte 2725800
binding size (1, 3)
size 3 dype <class 'numpy.float32'>
[0. 0. 0.]
memory out <pycuda._driver.DeviceAllocation object at 0x000001B9ED31BF40>
mem  <pycuda._driver.DeviceAllocation object at 0x000001B9ED31BAC0> buff  [[[ 1.3241715   1.4954191   1.5810429  ...  1.0501755   1.0501755
    1.0501755 ]
  [ 1.3070468   1.4611696   1.5639181  ...  1.0501755   1.0501755
    1.0501755 ]
  [ 1.2899221   1.4097953   1.5296686  ...  1.0501755   1.0501755
    1.0501755 ]
  ...
  [ 0.5364329   0.57068247  0.57068247 ...  0.57068247  0.57068247
    0.57068247]
  [ 0.5193082   0.5364329   0.5193082  ...  0.4850587   0.4850587
    0.4850587 ]
  [ 0.50218344  0.50218344  0.4850587  ...  0.46793392  0.45080918
    0.46793392]]

 [[ 1.4306723   1.6057423   1.6932774  ...  0.94047624  0.94047624
    0.94047624]
  [ 1.4131653   1.5707283   1.6757703  ...  0.94047624  0.94047624
    0.94047624]
  [ 1.3956583   1.5182073   1.6407562  ...  0.94047624  0.94047624
    0.94047624]
  ...
  [ 0.18767506  0.2226892   0.2401962  ...  0.3102242   0.3102242
    0.3102242 ]
  [ 0.17016806  0.18767506  0.18767506 ...  0.2226892   0.2226892
    0.2226892 ]
  [ 0.15266106  0.15266106  0.15266106 ...  0.2051822   0.18767506
    0.2051822 ]]

 [[ 1.3502399   1.5245317   1.6465361  ...  0.6182137   0.6182137
    0.6182137 ]
  [ 1.3328106   1.4896734   1.6291069  ...  0.6182137   0.6182137
    0.6182137 ]
  [ 1.3153814   1.4373858   1.5942485  ...  0.6182137   0.6182137
    0.6182137 ]
  ...
  [-0.41010883 -0.37525046 -0.32296288 ... -0.23581691 -0.23581691
   -0.23581691]
  [-0.42753804 -0.41010883 -0.37525046 ... -0.32296288 -0.32296288
   -0.32296288]
  [-0.44496724 -0.44496724 -0.41010883 ... -0.34039208 -0.35782126
   -0.34039208]]]
True
[0. 0. 0.]
<pycuda._driver.DeviceAllocation object at 0x000001B9ED31BF40>
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:10: DeprecationWarning: Use get_tensor_name instead.
  print(engine.get_binding_index("input"))
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:11: DeprecationWarning: Use get_tensor_name instead.
  context.set_binding_shape(engine.get_binding_index("input"), (1, 3, image_height, image_width))
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:11: DeprecationWarning: Use set_input_shape instead.
  context.set_binding_shape(engine.get_binding_index("input"), (1, 3, image_height, image_width))
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:16: DeprecationWarning: Use get_tensor_name instead.
  binding_idx = engine.get_binding_index(binding)
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:17: DeprecationWarning: Use get_tensor_shape instead.
  print("binding size",context.get_binding_shape(binding_idx))
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:18: DeprecationWarning: Use get_tensor_shape instead.
  size = trt.volume(context.get_binding_shape(binding_idx))
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:19: DeprecationWarning: Use get_tensor_dtype instead.
  dtype = trt.nptype(engine.get_binding_dtype(binding))
C:\Users\gj\AppData\Local\Temp\ipykernel_11580\158248581.py:21: DeprecationWarning: Use get_tensor_mode instead.
  if engine.binding_is_input(binding):
---------------------------------------------------------------------------
LogicError                                Traceback (most recent call last)
Cell In[6], line 3
      1 print("Running TensorRT inference for FCN-ResNet101")
      2 with load_engine(engine_file) as engine:
----> 3     infer(engine, input_file, output_file)

Cell In[4], line 46, in infer(engine, input_file, output_file)
     44     print(output_memory)
     45     # Synchronize the stream
---> 46     stream.synchronize()
     49 img =postprocess(np.reshape(output_buffer, (image_height, image_width)))
     51 print("Writing output image to file {}".format(output_file))

LogicError: cuStreamSynchronize failed: an illegal memory access was encountered

**Comment by JanuszL** [comment]
Hi @Abiganesh,

Thank you for reaching out. I'm afraid I don't see anything related to DALI your code sample. I think you should ask a question to the TRT team on [our NVIDIA forum](https://forums.developer.nvidia.com/).
