### ISSUE TITLE
CUDA runtime API error cudaErrorOperatingSystem

### ISSUE THREAD

**Issue by Luciennnnnnn** [NVIDIA/DALI#4852]
### Describe the question.

Hi, I encounter following error When I use following code testing my data loading procedure. Any suggestions for it?
I use DALI with cuda110

Error:
```text
Traceback (most recent call last):
  File "/gdata2/luoxin/projects/BasicSR/test_dali_dws_bapps.py", line 123, in <module>
    pipe.build()
  File "/opt/conda/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 820, in build
    self._pipe.Build(self._generate_build_args())
RuntimeError: Critical error when building pipeline:
Error when constructing operator: decoders__Image, instance name: "__Image_3", encountered:
CUDA runtime API error cudaErrorOperatingSystem (304):
OS call failed or operation not supported on this OS
Current pipeline object is no longer valid.
```
Code:
```python
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy
from nvidia.dali.pipeline import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

import os
import gc
import time

import torch

# Timing utilities
start_time = None


def start_timer():
    global start_time
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.reset_max_memory_allocated()
    torch.cuda.synchronize()
    start_time = time.time()


def end_timer_and_print(local_msg):
    torch.cuda.synchronize()
    end_time = time.time()

    print(local_msg, flush=True)
    print("Total execution time = {:.3f} sec".format(end_time - start_time), flush=True)
    print("Max memory used by tensors = {} bytes".format(torch.cuda.max_memory_allocated()), flush=True)


@pipeline_def
def bapps_dali_wds_pipeline(paths, index_paths, size, shard_id, num_shards, dali_cpu=False, is_training=True, interp_type=types.INTERP_CUBIC):

    p0, p1, ref, judge = fn.readers.webdataset(paths=paths,
                                            index_paths=index_paths,
                                            ext=["p0", "p1", "ref", 'judge'],
                                            dtypes=[types.UINT8, types.UINT8, types.UINT8, types.FLOAT],
                                            shard_id=shard_id,
                                            num_shards=num_shards,
                                            random_shuffle=is_training,
                                            initial_fill=1024,
                                            pad_last_batch=True,
                                            name="Reader",
                                            missing_component_behavior="error")
    dali_device = 'cpu' if dali_cpu else 'gpu'
    decoder_device = 'cpu' if dali_cpu else 'mixed'
    # ask nvJPEG to preallocate memory for the biggest sample in ImageNet for CPU and GPU to avoid reallocations in runtime
    device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
    host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
    # ask HW NVJPEG to allocate memory ahead for the biggest image in the data set to avoid reallocations in runtime
    preallocate_width_hint = 5980 if decoder_device == 'mixed' else 0
    preallocate_height_hint = 6430 if decoder_device == 'mixed' else 0

    p0 = fn.decoders.image(p0,
                            device=decoder_device, output_type=types.RGB,
                            device_memory_padding=device_memory_padding,
                            host_memory_padding=host_memory_padding,
                            preallocate_width_hint=preallocate_width_hint,
                            preallocate_height_hint=preallocate_height_hint)

    p1 = fn.decoders.image(p1,
                            device=decoder_device, output_type=types.RGB,
                            device_memory_padding=device_memory_padding,
                            host_memory_padding=host_memory_padding,
                            preallocate_width_hint=preallocate_width_hint,
                            preallocate_height_hint=preallocate_height_hint)

    ref = fn.decoders.image(ref,
                            device=decoder_device, output_type=types.RGB,
                            device_memory_padding=device_memory_padding,
                            host_memory_padding=host_memory_padding,
                            preallocate_width_hint=preallocate_width_hint,
                            preallocate_height_hint=preallocate_height_hint)

    p0 = fn.resize(p0, device=dali_device, resize_x=size, resize_y=size, interp_type=interp_type)
    p1 = fn.resize(p1, device=dali_device, resize_x=size, resize_y=size, interp_type=interp_type)
    ref = fn.resize(ref, device=dali_device, resize_x=size, resize_y=size, interp_type=interp_type)

    p0 = fn.crop_mirror_normalize(p0.gpu(), dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])
    p1 = fn.crop_mirror_normalize(p1.gpu(), dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])
    ref = fn.crop_mirror_normalize(ref.gpu(), dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])

    judge = fn.expand_dims(judge.gpu(), axes=[1, 2])
    return p0, p1, ref, judge


root_dir = os.path.dirname(os.path.abspath(__file__))
root = os.path.join(root_dir, 'datasets/BAPPS_wds')

dataroots = [os.path.join(root, '2afc/train/cnn'),
             os.path.join(root, '2afc/train/mix'),
             os.path.join(root, '2afc/train/traditional')]

paths = []
index_paths = []

for dataroot in dataroots:
    file_names = sorted(os.listdir(dataroot))

    for file_name in file_names:
        name, ext = os.path.splitext(file_name)
        if ext == '.tar':
            if f"{name}.index" in file_names:
                paths.append(os.path.join(dataroot, file_name))
                index_paths.append(os.path.join(dataroot, f"{name}.index"))


pipe = bapps_dali_wds_pipeline(batch_size=128,
                                num_threads=8,
                                device_id=0,
                                seed=0,
                                paths=paths,
                                index_paths=index_paths,
                                size=64,
                                dali_cpu=False,
                                shard_id=0,
                                num_shards=1,
                                is_training=True,
                                interp_type=types.INTERP_CUBIC)
pipe.build()
data_loader = DALIGenericIterator(pipe, ["p0", "p1", "ref", "judge"], reader_name="Reader", last_batch_policy=LastBatchPolicy.DROP, auto_reset=True)

print('finish building pipeline...', flush=True)

for i, data in enumerate(data_loader):
    print(data)
    if i + 1 == 2:
        break

start_timer()
for i, data in enumerate(data_loader):
    if (i + 1) % 100 == 0:
        end_timer_and_print('data loading...')
        start_timer()
    if (i + 1) % 500 == 0:
        break
```
Environments:
```text
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.27

Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 470.63.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7402 24-Core Processor
Stepping:            0
CPU MHz:             2800.000
CPU max MHz:         2800.0000
CPU min MHz:         1500.0000
BogoMIPS:            5599.82
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate avic fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold overflow_recov succor smca
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by LuoXin-s** [comment]
I found the problem is in `device_memory_padding`, `host_memory_padding`, `preallocate_width_hint`, `preallocate_height_hint`. I set these numbers as in ImageNet, so it leads to errors.

Is there any methods I can get these numbers for custom datasets?

**Comment by JanuszL** [comment]
Hi @LuoXin-s,

To learn the padding value please set `memory_stats=True`, regarding the size hints you need to learn it directly from your data set.
When it comes to the error, is it fully reproducible? Can you assemble a simple sample based on https://github.com/NVIDIA/DALI_extra data, so we can run it on our end?

**Comment by JanuszL** [comment]
Closing as stalled.
